dictionary:
  SIMPLE:
    - word: "дом"
      hint: "Место, где живут люди"
    - word: "кот"
      hint: "Домашнее животное"
    - word: "мяч"
      hint: "Сферический объект для игр"
    - word: "солнце"
      hint: "Звезда, дающая свет и тепло Земле"
    - word: "книга"
      hint: "Источник знаний, состоит из страниц"
    - word: "река"
      hint: "Водный поток, текущий в естественном русле"
    - word: "ночь"
      hint: "Время суток между вечером и утром"
    - word: "мышь"
      hint: "Небольшой грызун или компьютерный аксессуар"
    - word: "море"
      hint: "Большой водоём с солёной водой"
    - word: "жена"
      hint: "Супруга"

  MIDDLE:
    - word: "веревка"
      hint: "Приспособление для связывания или сушки белья"
    - word: "дуршлаг"
      hint: "Кухонный инструмент с дырочками для отцеживания воды"
    - word: "шпроты"
      hint: "Мелкая копчёная рыба в масле, часто в банках"
    - word: "буцефал"
      hint: "Имя знаменитого коня Александра Македонского"
    - word: "жульен"
      hint: "Блюдо, запечённое в специальной небольшой посуде"
    - word: "иероглиф"
      hint: "Древний знак для письма, например, в Египте или Китае"
    - word: "шаман"
      hint: "Духовный лидер, общающийся с духами в традиционных культурах"
    - word: "процедура"
      hint: "Последовательность действий для достижения результата"
    - word: "марионетка"
      hint: "Кукла, которой управляют с помощью нитей"
    - word: "блендер"
      hint: "Кухонный электроприбор для измельчения продуктов"

  HARD:
    - word: "галлюциноген"
      hint: "Вещество, вызывающее видения и искажающее восприятие"
    - word: "рефрижиратор"
      hint: "Устройство для охлаждения, синоним холодильника"
    - word: "чехословакия"
      hint: "Название бывшего государства в Центральной Европе"
    - word: "эксклюзивность"
      hint: "Свойство, означающее уникальность и неповторимость"
    - word: "имиджмейкер"
      hint: "Специалист по созданию публичного образа"
    - word: "ассенизатор"
      hint: "Работник, занимающийся откачкой нечистот из выгребных ям"
    - word: "перпендикуляр"
      hint: "Геометрический термин, обозначающий прямую, составляющую прямой угол с другой прямой"
    - word: "хиппопотомонстросесквипедалиофобия"
      hint: "Ироничное название боязни длинных слов"
